tasks:
  - before: |
      npm install &
      export MO_DEV_HIDE_URLS=1 # hide Candid UI links
      export PATH="$HOME/bin:$PATH"
      echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
      sudo apt-get install -q -y libunwind-dev
      DFXVM_INIT_YES=1 sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
      source "$HOME/.local/share/dfx/env"
      dfx start --background --clean      
      npm i
      dfx identity new gitpod_dev --storage-mode=plaintext
      dfx identity use gitpod_dev
      npm i -g ic-mops
      mops install
    init: |
      dfx deploy
    command: |
      dfx deploy

vscode:
  extensions:
    - dfinity-foundation.vscode-motoko

ports:
  - name: Replica
    port: 4943
    visibility: public
    onOpen: ignore
  - name: Dev Server
    port: 3000
    visibility: public
    onOpen: open-browser
